---
title: "HR 데이터분석"
---

-   데이터 : kaggle datasets <https://www.kaggle.com/datasets/saurabh0/human-resources-employee-attrition>.
-   주제 : Human Resource Analytics data를 통한 이직 결정 요소 파악 및 이직 예측하기.
-   분석기법 : 로지스틱 회귀분석.
-   종속변수 : left 퇴사여부 (Target 값)
-   독립변수 : 

1.  데이터 전처리
1-1. 데이터 불러오기 및 확인
```{r}
library(readxl)
library(VIM)
library(missForest)
library(mice)
df <- read.csv('Human_Resources_Employee_Attrition.csv')
str(df)
```

1-2. 수치형 칼럼 카테고리형으로 변경 및 결측치 처리
```{r}
df$left <- factor(df$left)
df$department <- factor(df$department)
df$salary <- factor(df$salary)
str(df)
```
```{r}
# 퇴사자(1) 비율이 20% 이상이여서 분석 진행
prop.table(table(df$left))
barplot(table(df$left), col=c('skyblue','tomato'))
```

2. 데이터 분석
2-1. 범주형 독립변수별 퇴사률 도출
```{r}
dep.ad <- prop.table(table(df$left, df$department), margin=2)
salary.ad <- prop.table(table(df$left, df$salary), margin = 2)
barplot(dep.ad*100, col = c('skyblue','tomato'))
text(1:13, dep.ad[1,]*100+4.2, paste(as.character(round(dep.ad[2,], 2)*100),'%'))
barplot(salary.ad*100, col = c('skyblue','tomato'))
text(c(0.7, 1.9, 3.1), salary.ad[1,]*100+4.2, paste(as.character(round(salary.ad[2,], 2)*100),'%'))

```



```{r}

```

